### ISSUE TITLE
External Frontend Framework

### ISSUE THREAD

**Issue by gutorsantos** [GeoNode/geonode-vision#1]
Hello,

I'm working on a project where I would like to use geonode only as a backend and use an external framework for frontend development. I read the part of the documentation related to [Frontend Development](https://docs.geonode.org/en/master/contribute/frontend-development/index.html) but from what I understand I am still restricted to the django directory structure which is not interesting for project management.

**Comment by gamesbook** [comment]
If you're not using any of GeoNode's front-end, you may only need the API - https://docs.geonode.org/en/master/api/V2/index.html

**Comment by gutorsantos** [comment]
Thx @gamesbook, i will see this!

I ended up confusing the repositories, I repositioned the issue in the official geonode repository so I am closing this issue. I was not able to delete it so it would be of interest to someone to delete it is okay.
